---
user: gabe
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_osx: yes

dotfiles_repo: https://github.com/gabe-ochoa/dotfiles.git
dotfiles_push_url: git@github.com:gabe-ochoa/dotfiles.git
dotfiles_repo_local_destination: ~/code/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - zsh
  - zsh-completions
  - ccat
  - cfssl
  - ctags
  - dockutil
  - fzf
  - git
  - git-open
  - gpg
  - jq
  - kubernetes-cli
  - mas
  - node
  - rbenv
  - readline
  - ruby
  - go
  - stern
  - the_silver_searcher
  - vim
  - watch
  - wget
  - font-hack-nerd-font
  - kubetail

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - caskroom/fonts
  - johanhaleby/kubetail

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - alfred
  - google-chrome
  - slack
  - virtualbox
  - iterm2
  - spectacle
  - dashlane
  - little-snitch
  - micro-snitch
  - insomniax
  - beardedspice
  - xquartz

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: "gabeochoa@gmail.com"
mas_password: ""

osx_script: "/Users/gochoa/.osx --no-restart"

gem_packages:
  - name: bundler
    state: present  # present/absent/latest, default: present

composer_packages: []
npm_packages: []
pip_packages:
  - name: virtualenv
    state: present
extra_packages_cmds:
  - cmd: pip install virtualenvwrapper --ignore-installed six

dockitems_to_remove:
  - Launchpad
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Pages
  - Photos
  - FaceTime
  - iBooks
  - App Store
  - System Preferences
  - Downloads

dockitems_to_persist:
  - name: Sublime Text
    path: /Applications/Sublime Text.app
    position: 1
  - name: iTerm
    path: /Applications/iTerm.app
    position: 2
  - name: Dash
    path: /Applications/Dash.app
    position: 3
  - name: Google Chrome
    path: /Applications/Google Chrome.app
    position: 4
  - name: Slack
    path: /Applications/Slack.app
    position: 5
  - name: iA Writer
    path: /Applications/iA Writer.app
    position: 6


# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: ["git clone --recursive git@github.com:gabe-ochoa/prezto.git '${ZDOTDIR:-$HOME}/.zprezto'"]
