---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_osx: yes

dotfiles_repo: https://github.com/jayson/dotfiles.git
dotfiles_repo_local_destinationdotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/projects/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - cfssl
  - ctags
  - fzf
  - git
  - kubernetes-cli
  - mas
  - node
  - rbenv
  - readline
  - ruby
  - the_silver_searcher
  - vim
  - watch
  - wget

homebrew_taps:
  - homebrew/core
  - caskroom/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # - docker
  # - alfred
  # - google-chrome
  # - slack
  - vagrant
  - virtualbox

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: "jaysonpaul@gmail.com"
mas_password: ""

osx_script: "~/.osx --no-restart"

gem_packages:
  - name: bundler
    state: present # present/absent/latest, default: present

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
