---
- hosts: all
  connection: local

  vars_files:
    - config.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']
    - role: dock
      tags: ['dock']
    - role: iterm
      tags: ['iterm']

  tasks:
    - include: tasks/ansible-setup.yml

    - include: tasks/sudoers.yml
      when: configure_sudoers

    - include: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - include: tasks/extra-packages.yml
      tags: ['extra-packages']

    - include: tasks/keyboard.yml
      tags: ['keyboard']

    - name: Run configured post-provision ansible task files.
      include: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
