---
- name: Clone dotfiles
  git: repo={{ dotfiles_repo }}.git dest={{ dotfiles_repo_local_destination }} recursive=yes update=no

- name: Set zsh as shell
  user: name=$user shell=/bin/zsh

- name: Run dotfiles install
  command: ./install chdir="{{ dotfiles_repo_local_destination }}"

- name: Install Vim Plugins
  command: vim +PlugInstall +qall
