---
- name: Clone dotfiles
  git: repo={{ dotfiles_repo }}.git dest={{ dotfiles_repo_local_destination }} recursive=yes update=yes

- name: Set zsh as shell
  become: yes
  user: name={{ user }} shell=/bin/zsh

- name: Run dotfiles install
  command: ./install chdir="{{ dotfiles_repo_local_destination }}"

- name: Install Vim Plugins
  command: vim +PlugInstall +qall
