---
- name: Set custom preferences folder
  command: 'defaults write com.googlecode.iterm2 PrefsCustomFolder "/Users/jpaul/projects/jayson-mac-ansible/roles/iterm/files/"'

- name: Set load from custom preferences folder
  command: defaults write LoadPrefsFromCustomFolder -int 1
